SELECT new_id,new_cat,
    SUM(new_id) OVER(ORDER BY new_id ROWS BETWEEN UNBOUNDED PRECEEDING AND UNBOUNDED FOLLOWING) AS "Total",
    AVG(new_id) OVER(ORDER BY new_id ROWS BETWEEN UNBOUNDED PRECEEDING AND UNBOUNDED FOLLOWING) AS "Average",
    COUNT(new_id) OVER(ORDER BY new_id ROWS BETWEEN UNBOUNDED PRECEEDING AND UNBOUNDED FOLLOWING) AS "Count",
    MIN(new_id) OVER(ORDER BY new_id ROWS BETWEEN UNBOUNDED PRECEEDING AND UNBOUNDED FOLLOWING) AS "Min",
    MAX(new_id) OVER(ORDER BY new_id ROWS BETWEEN UNBOUNDED PRECEEDING AND UNBOUNDED FOLLOWING) AS "Max",
FROM test_data


-- NOTE: Above we have used: "ROWS BETWEEN UNBOUNDED PRECEEDING AND UNBOUNDED FOLLOWING" which will give a SINGLE output based on all INPUT Values/PARTITION (if used)