# Base image
FROM python:3.13-slim

# Workdir
WORKDIR /app

# Copy requirements first
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files 
COPY . .

# Expose FastAPI port
EXPOSE 8000

# RUN FastAPI app
CMD ["uvicorn","insurance_api.app:app","--host","0.0.0.0","--port","8000"]